version: '3'
services:

  timescale:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432:5432"

  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:d1c2b50ba47046c2dd0bcd786970469e21d6998b08ad09b56da8fb17cd267ef6'
    restart: always
    command: [ '-experimental', '-logLevel', 'DEBUG' ]
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_TROE: 'TRUE'
      ORIONLD_TROE_USER: 'postgres'
      ORIONLD_TROE_PWD: 'password'
      ORIONLD_TROE_HOST: 'timescale'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      mongodb:
        condition: service_healthy
      timescale:
        condition: service_healthy
    ports:
      - '1026:1026'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1026/ngsi-ld/v1/types" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  mintaka:
    image: fiware/mintaka:0.7.0
    restart: always
    depends_on:
      orion-ld:
        condition: service_healthy
    environment:
      DATASOURCES_DEFAULT_HOST: 'timescale'
      DATASOURCES_DEFAULT_USERNAME: 'postgres'
      DATASOURCES_DEFAULT_PASSWORD: 'password'
      DATASOURCES_DEFAULT_DATABASE: 'orion'
      BASEPATH: '/ngsi-ld/v1'
#    volumes:
#      - './configs/diwise/mintaka-logging.xml:/app/resources/logback.xml'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    ports:
      - "8080"

  mongodb:
    image: mongo:5
    healthcheck:
      test: [ "CMD-SHELL", "mongo", "--port", "27017", "-u", "admin", "-p", "password", "--eval", "\"db.adminCommand('ping')\"" ]
      interval: 5s
      timeout: 1s
      retries: 12
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data

volumes:
  rabbitmq_data:
    driver: local
  mongo-db: ~